version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./serving
      dockerfile: Dockerfile
    ports:
      - 5001:5000

  tf_serve:
    container_name: diamonds
    build:
      context: ./model/
      dockerfile: Dockerfile
    volumes:
      - ./model/diamonds:/models/diamonds
    ports:
      - 8500:8500
      - 8501:8501